title: Meindra Rahardian
description: Front-end developer based in Tulungagung, Indonesia
email: meindra.me@gmail.com
twitter: lubangkelinci
github: meindra
baseurl: ""
markdown: kramdown
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock