title: Meindra Rahardian
description: Front-end developer based in Tulungagung, Indonesia
email: meindra.me@gmail.com
github: meindra
linkedin: meindra
baseurl: ''
markdown: kramdown
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  - scope:
      type: 'posts'
    values:
      layout: 'post'
      is_post: true
      permalink: /:title/
